application: nusmodmaven
version: 1
runtime: python27
api_version: 1
threadsafe: true

##default_expiration: "2h"

handlers:

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

#- url: /sitemap
#  static_dir: sitemap

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /.*
  script: index.app

libraries:
- name: jinja2
  version: 2.6
- name: webapp2
  version: "2.5.2"